### ISSUE TITLE
LoginSchema::new always succeeds

### ISSUE THREAD

**Issue by SpecificProtagonist** [polyphony-chat/chorus#127]
~~It should check both username & password length~~

→ shouldn't return a result

**Comment by bitfl0wer** [comment]
No, it should not. The username length and password length are two properties which get validated by the spacebar server. Some spacebar servers do not require a password to register/log in at all. Some do. This is not on us to check, especially because, as far as I know, the server does not tell you this information. You just have to try and check.

**Comment by bitfl0wer** [comment]
That's true. Those are old remnants from when i first started working on this
